version: '3.9'

services:
  portfolio_rn:
    build:
      context: .
    env_file:
      - .env
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfoliorn.rule=Host(`portfolio.roymond.net`)"
      - "traefik.http.routers.portfoliorn.entrypoints=websecure"
      - "traefik.http.routers.portfoliorn.tls.certresolver=letsEncrypt"
      - "traefik.http.services.portfoliorn.loadbalancer.server.port=9022"
    ports:
      - "9022:9022"
    container_name: portfolio_rn

networks:
  container-dmz:
    external: true