version: '3.9'

services:
  portfolio_rn:
    build:
      context: .
    env_file:
      - .env
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfoliorn.rule=Host(`${DOMAIN_NAME}`)||Host(`www.${DOMAIN_NAME}`))"
      - "traefik.http.routers.portfoliorn.entrypoints=websecure"
      - "traefik.http.routers.portfoliorn.tls.certresolver=production"
      - "traefik.http.services.portfoliorn.loadbalancer.server.port=${PORT_NUMBER}"
    ports:
      - "${PORT_NUMBER}:${PORT_NUMBER}"
    container_name: portfolio_rn

networks:
  container-dmz:
    external: true